Neighborhood.create(name: "Cattail North", file_id: "2012_1", drop_location: 2)
Neighborhood.create(name: "Cattail South", file_id: "2012_2", drop_location: 2)
Neighborhood.create(name: "Baxter Ln - Harper Pucket - Lolo Way", file_id: "2012_3", drop_location: 2)
Neighborhood.create(name: "Baxter Ln - N 27th (Brentwood)", file_id: "2012_4", drop_location: 2)
Neighborhood.create(name: "Westgate North", file_id: "2012_5", drop_location: 2)
Neighborhood.create(name: "Durston - Rosa - West Oak", file_id: "2012_6", drop_location: 2)
Neighborhood.create(name: "Harvest Creek NW", file_id: "2012_7", drop_location: 2)
Neighborhood.create(name: "Harvest Creek SE", file_id: "2012_8", drop_location: 2)
Neighborhood.create(name: "Harvest Creek - New Holland - Rose - Oliver - Lily", file_id: "2012_9", drop_location: 2)
Neighborhood.create(name: "Durston Meadows - Buckrake - Case - Harris", file_id: "2012_10", drop_location: 4)
Neighborhood.create(name: "Durston Meadows - Aster - Daffodil - Snapdragon", file_id: "2012_11", drop_location: 4)
Neighborhood.create(name: "Walton Homestead - North 15th", file_id: "2012_12", drop_location: 4)
Neighborhood.create(name: "Walton Homestead - South 15th", file_id: "2012_13", drop_location: 4)
Neighborhood.create(name: "Ferguson Meadows - Stafford - Cascade - Alexander", file_id: "2012_14", drop_location: 4)
Neighborhood.create(name: "Ferguson Meadows - Hanley - Monroe - Cover", file_id: "2012_15", drop_location: 4)
Neighborhood.create(name: "Flathead and Teton - Broadwater - Spruce Meadows", file_id: "2012_16", drop_location: 4)
Neighborhood.create(name: "Sheridan Ave - Sheridan Place - N and S Sweetgrass", file_id: "2012_17", drop_location: 4)
Neighborhood.create(name: "Hunters Way between Mendenhall and Durston", file_id: "2012_18", drop_location: 4)
Neighborhood.create(name: "Hunters Way - Meghans Way - Sunlight - Western", file_id: "2012_19", drop_location: 4)
Neighborhood.create(name: "Willowbrook Condos - N 23rd", file_id: "2012_20", drop_location: 2)
Neighborhood.create(name: "N 15th - N 16th - N 17th - N 18th", file_id: "2012_21", drop_location: 2)
Neighborhood.create(name: "Slough Creek - Stillwater Creek - Pallisade", file_id: "2012_22", drop_location: 4)
Neighborhood.create(name: "Valley Commons - Fallon - S Ferguson - Babcock", file_id: "2012_23", drop_location: 4)
Neighborhood.create(name: "Valley Commons - Fallon - Praire - Babcock", file_id: "2012_24", drop_location: 2)
Neighborhood.create(name: "Pond Row - Babcock - Donna - White Oak", file_id: "2012_25", drop_location: 2)
Neighborhood.create(name: "W Koch - S 20th - S 16th - S 15th", file_id: "2012_26", drop_location: 3)
Neighborhood.create(name: "W Dickerson - Willowbrook Condos", file_id: "2012_27", drop_location: 3)
Neighborhood.create(name: "Loyal Gardens", file_id: "2012_28", drop_location: 4)
Neighborhood.create(name: "MSU Student Housing West", file_id: "2012_29", drop_location: 4)
Neighborhood.create(name: "MSU Student Housing East", file_id: "2012_30", drop_location: 4)
Neighborhood.create(name: "Hill - Highland - Spring Creek", file_id: "2012_31", drop_location: 3)
Neighborhood.create(name: "Westridge North", file_id: "2012_32", drop_location: 3)
Neighborhood.create(name: "Westridge South", file_id: "2012_33", drop_location: 3)
Neighborhood.create(name: "Alder Creek", file_id: "2012_34", drop_location: 3)
Neighborhood.create(name: "Westfield North", file_id: "2012_35", drop_location: 3)
Neighborhood.create(name: "Wagonwheel North", file_id: "2012_36", drop_location: 3)
Neighborhood.create(name: "Gardner Park", file_id: "2012_37", drop_location: 1)
Neighborhood.create(name: "Hitching Post South", file_id: "2012_38", drop_location: 1)
Neighborhood.create(name: "Sourdough Ridge", file_id: "2012_39", drop_location: 3)
Neighborhood.create(name: "Painted Hills", file_id: "2012_40", drop_location: 1)
Neighborhood.create(name: "Highland", file_id: "2012_41", drop_location: 1)
Neighborhood.create(name: "N Pinecrest - N Cedarview", file_id: "2012_42", drop_location: 1)
Neighborhood.create(name: "Holly - Ash", file_id: "2012_43", drop_location: 1)
Neighborhood.create(name: "N Wallace - Mendenhall", file_id: "2012_44", drop_location: 1)
Neighborhood.create(name: "N 8th - N 9th", file_id: "2012_45", drop_location: 1)
Neighborhood.create(name: "3rd - 4th - 5th - 6th between Peach and Villard", file_id: "2012_46", drop_location: 1)
Neighborhood.create(name: "Peach - Grand - Black - Villard", file_id: "2012_47", drop_location: 1)
Neighborhood.create(name: "Peach - 3rd - Tamarack - Tracy", file_id: "2012_48", drop_location: 4)
Neighborhood.create(name: "Main - 7th - Villard - Willson", file_id: "2012_49", drop_location: 1)
Neighborhood.create(name: "Peach - Black - Tamarack - Rouse", file_id: "2012_50", drop_location: 1)
Neighborhood.create(name: "Beall Park Area", file_id: "2012_51", drop_location: 1)
Neighborhood.create(name: "Peach - Rouse - Tamarack - Front", file_id: "2012_53", drop_location: 1)
Neighborhood.create(name: "Lamme - Rouse - Peach - Church", file_id: "2012_54", drop_location: 1)
Neighborhood.create(name: "Kock - 15th - Babcock - 11th", file_id: "2012_55", drop_location: 4)
Neighborhood.create(name: "College - Dickerson - 8th", file_id: "2012_56", drop_location: 4)
Neighborhood.create(name: "Story - 15th - Koch - 8th", file_id: "2012_57", drop_location: 1)
Neighborhood.create(name: "Olive - 11th - Main - 4th", file_id: "2012_58", drop_location: 1)
Neighborhood.create(name: "Koch - 11th - Curtiss", file_id: "2012_59", drop_location: 3)
Neighborhood.create(name: "Dickerson - 8th - Story - Willson", file_id: "2012_60", drop_location: 1)
Neighborhood.create(name: "College - 8th - Alderson - Willson", file_id: "2012_61", drop_location: 1)
Neighborhood.create(name: "Koch - 3rd - Olive - Lindley Pl", file_id: "2012_62", drop_location: 1)
Neighborhood.create(name: "Willson - Tracy - College - Koch", file_id: "2012_63", drop_location: 1)
Neighborhood.create(name: "Cleveland - 8th - Harrison - 3rd", file_id: "2012_64", drop_location: 1)
Neighborhood.create(name: "Garfield - 7th - Arthur - Willson", file_id: "2012_65", drop_location: 3)
Neighborhood.create(name: "Garfield - Willson - College - Black", file_id: "2012_66", drop_location: 3)
Neighborhood.create(name: "Mason - Black - Cleveland - Rouse", file_id: "2012_67", drop_location: 3)
Neighborhood.create(name: "Grant - 6th - Hayes - Willson", file_id: "2012_68", drop_location: 3)
Neighborhood.create(name: "Bonner - Rouse - Babcock - Wallace", file_id: "2012_69", drop_location: 3)
Neighborhood.create(name: "Meadow Creek", file_id: "2012_70", drop_location: 3)
Neighborhood.create(name: "Fieldview Circle", file_id: "2012_71", drop_location: 3)
Neighborhood.create(name: "Westgate South", file_id: "2012_72", drop_location: 3)
Neighborhood.create(name: "Harvest Creek SW", file_id: "2012_73", drop_location: 2)
Neighborhood.create(name: "Harvest Creek NE", file_id: "2012_74", drop_location: 2)
Neighborhood.create(name: "Harvest Creek - New Holland - Median - Durham", file_id: "2012_75", drop_location: 2)
Neighborhood.create(name: "Brentwood - Woodland - Maplewood - Mountain Ash", file_id: "2012_76", drop_location: 2)
Neighborhood.create(name: "Mineral - Sanders between Durston and Babcock", file_id: "2012_77", drop_location: 2)
Neighborhood.create(name: "Yellowstone - Durston - Babcock", file_id: "2012_78", drop_location: 2)
Neighborhood.create(name: "Babcock - Cameahwait - Droulliard", file_id: "2012_79", drop_location: 2)
Neighborhood.create(name: "Babcock - Michael Grove", file_id: "2012_80", drop_location: 2)
Neighborhood.create(name: "Villard - Michael Grove", file_id: "2012_81", drop_location: 2)
Neighborhood.create(name: "25th - Mendenhall - Durston", file_id: "2012_82", drop_location: 2)
Neighborhood.create(name: "Babcock - 24th - Beall", file_id: "2012_83", drop_location: 4)
Neighborhood.create(name: "19th - 20th - 21st between Durston and Beall", file_id: "2012_84", drop_location: 2)
Neighborhood.create(name: "Arnold - Circle", file_id: "2012_85", drop_location: 3)
Neighborhood.create(name: "Graf - 3rd - Henderson", file_id: "2012_86", drop_location: 3)
Neighborhood.create(name: "Wagonwheel East", file_id: "2012_88", drop_location: 3)
Neighborhood.create(name: "Sundance Springs", file_id: "2012_89", drop_location: 3)
Neighborhood.create(name: "Cedarview - Spruce", file_id: "2012_90", drop_location: 3)
Neighborhood.create(name: "OConnell - Kenyon", file_id: "2012_91", drop_location: 3)
Neighborhood.create(name: "Cherry - Firecrest - Ash - Maple - Holly", file_id: "2012_92", drop_location: 1)
Neighborhood.create(name: "Bozeman Trail", file_id: "2012_93", drop_location: 1)
Neighborhood.create(name: "Bogart Neighborhood", file_id: "2012_94", drop_location: 1)
Neighborhood.create(name: "N 10th - N 11th", file_id: "2012_95", drop_location: 2)
Neighborhood.create(name: "Village Downtown", file_id: "2012_97", drop_location: 1)
Neighborhood.create(name: "Koch - 15th - Babcock - 11th", file_id: "2012_98", drop_location: 3)
Neighborhood.create(name: "Alderson - Black - Story - Dell Pl", file_id: "2012_99", drop_location: 1)
Neighborhood.create(name: "Accola - Hoffman - Rouse", file_id: "2012_100", drop_location: 1)
Neighborhood.create(name: "Kagy - Greek Way - 3rd - Grand", file_id: "2012_101", drop_location: 3)
Neighborhood.create(name: "Elk Grove 3", file_id: "2012_102", drop_location: 4)
Neighborhood.create(name: "Elk Grove 2", file_id: "2012_103", drop_location: 4)
Neighborhood.create(name: "Elk Grove 1", file_id: "2012_104", drop_location: 4)
Neighborhood.create(name: "River Rock - Magnolia - Thorpe", file_id: "2012_105", drop_location: 5)
Neighborhood.create(name: "River Rock - West Shore - Shallow Brook - Green Tree", file_id: "2012_106", drop_location: 5)
Neighborhood.create(name: "River Rock - Royal - Engberg - Shallow Brook", file_id: "2012_107", drop_location: 5)
Neighborhood.create(name: "River Rock - Pebble Brook - West Shore", file_id: "2012_108", drop_location: 5)
Neighborhood.create(name: "River Rock - Amsterdam - Sibley - Thorpe", file_id: "2012_109", drop_location: 5)
Neighborhood.create(name: "River Rock - Woodsman - Thorpe" , file_id: "2012_110", drop_location: 5)
Neighborhood.create(name: "Happy - Golden West - Westwood - Cruiser", file_id: "2012_111", drop_location: 5)
Neighborhood.create(name: "Golden West - Jackrabbit - Cruiser - Spooner", file_id: "2012_112", drop_location: 5)
Neighborhood.create(name: "Westwood Circle - Oakwood - Jackrabbit", file_id: "2012_113", drop_location: 5)
Neighborhood.create(name: "Mayfair - Jackrabbit - Golden West", file_id: "2012_114", drop_location: 5)
Neighborhood.create(name: "Frontage - 13th - Park - 9th", file_id: "2012_115", drop_location: 5)
Neighborhood.create(name: "Frontage - 9th - Allison - 6th", file_id: "2012_116", drop_location: 5)
Neighborhood.create(name: "McEwen - Spooner - Al", file_id: "2012_117", drop_location: 5)
Neighborhood.create(name: "Central - Jackrabbit - Triple Crown - Spooner", file_id: "2012_118", drop_location: 5)
Neighborhood.create(name: "Central - Hoffman - Cameron - Weaver", file_id: "2012_119", drop_location: 5)
Neighborhood.create(name: "Central - Weaver - Cameron", file_id: "2012_120", drop_location: 5)
Neighborhood.create(name: "Rosebud - Oregon - Madison", file_id: "2012_121", drop_location: 5)
Neighborhood.create(name: "Silverbow - Oregon - Northern Pacific", file_id: "2012_122", drop_location: 5)
Neighborhood.create(name: "Yellowstone - Oregon - Silverbow", file_id: "2012_123", drop_location: 5)
Neighborhood.create(name: "Stiles - Rosebud - Jeanette Pl", file_id: "2012_124", drop_location: 5)
Neighborhood.create(name: "Idaho - Las Campanas - Wyoming", file_id: "2012_125", drop_location: 5)
Neighborhood.create(name: "Meadowbrook Estates South", file_id: "2012_127", drop_location: 4)
Neighborhood.create(name: "Meadowbrook Estates North", file_id: "2012_128", drop_location: 4)
Neighborhood.create(name: "Middle Creek", file_id: "2012_129", drop_location: 4)
