Neighborhood.create(name: "Cattail North", file_id: "2012_1")
Neighborhood.create(name: "Cattail South", file_id: "2012_2")
Neighborhood.create(name: "Baxter Ln - Harper Pucket - Lolo Way", file_id: "2012_3")
Neighborhood.create(name: "Baxter Ln - N 27th (Brentwood)", file_id: "2012_4")
Neighborhood.create(name: "Westgate North", file_id: "2012_5")
Neighborhood.create(name: "Durston - Rosa - West Oak", file_id: "2012_6")
Neighborhood.create(name: "Harvest Creek NW", file_id: "2012_7")
Neighborhood.create(name: "Harvest Creek SE", file_id: "2012_8")
Neighborhood.create(name: "Harvest Creek - New Holland - Rose - Oliver - Lily", file_id: "2012_9")
Neighborhood.create(name: "Durston Meadows - Buckrake - Case - Harris", file_id: "2012_10")
Neighborhood.create(name: "Durston Meadows - Aster - Daffodil - Snapdragon", file_id: "2012_11")
Neighborhood.create(name: "Walton Homestead - North 15th", file_id: "2012_12")
Neighborhood.create(name: "Walton Homestead - South 15th", file_id: "2012_13")
Neighborhood.create(name: "Ferguson Meadows - Stafford - Cascade - Alexander", file_id: "2012_14")
Neighborhood.create(name: "Ferguson Meadows - Hanley - Monroe - Cover", file_id: "2012_15")
Neighborhood.create(name: "Flathead and Teton - Broadwater - Spruce Meadows", file_id: "2012_16")
Neighborhood.create(name: "Sheridan Ave - Sheridan Place - N and S Sweetgrass", file_id: "2012_17")
Neighborhood.create(name: "Hunters Way between Mendenhall and Durston", file_id: "2012_18")
Neighborhood.create(name: "Hunters Way - Meghans Way - Sunlight - Western", file_id: "2012_19")
Neighborhood.create(name: "Willowbrook Condos - N 23rd", file_id: "2012_20")
Neighborhood.create(name: "N 15th - N 16th - N 17th - N 18th", file_id: "2012_21")
Neighborhood.create(name: "Slough Creek - Stillwater Creek - Pallisade", file_id: "2012_22")
Neighborhood.create(name: "Valley Commons - Fallon - S Ferguson - Babcock", file_id: "2012_23")
Neighborhood.create(name: "Valley Commons - Fallon - Praire - Babcock", file_id: "2012_24")
Neighborhood.create(name: "Pond Row - Babcock - Donna - White Oak", file_id: "2012_25")
Neighborhood.create(name: "W Koch - S 20th - S 16th - S 15th", file_id: "2012_26")
Neighborhood.create(name: "W Dickerson - Willowbrook Condos", file_id: "2012_27")
Neighborhood.create(name: "Loyal Gardens", file_id: "2012_28")
Neighborhood.create(name: "MSU Student Housing West", file_id: "2012_29")
Neighborhood.create(name: "MSU Student Housing East", file_id: "2012_30")
Neighborhood.create(name: "Hill - Highland - Spring Creek", file_id: "2012_31")
Neighborhood.create(name: "Westridge North", file_id: "2012_32")
Neighborhood.create(name: "Westridge South", file_id: "2012_33")
Neighborhood.create(name: "Alder Creek", file_id: "2012_34")
Neighborhood.create(name: "Westfield North", file_id: "2012_35")
Neighborhood.create(name: "Wagonwheel North", file_id: "2012_36")
Neighborhood.create(name: "Gardner Park", file_id: "2012_37")
Neighborhood.create(name: "Hitching Post South", file_id: "2012_38")
Neighborhood.create(name: "Sourdough Ridge", file_id: "2012_39")
Neighborhood.create(name: "Painted Hills", file_id: "2012_40")
Neighborhood.create(name: "Highland", file_id: "2012_41")
Neighborhood.create(name: "N Pinecrest - N Cedarview", file_id: "2012_42")
Neighborhood.create(name: "Holly - Ash", file_id: "2012_43")
Neighborhood.create(name: "N Wallace - Mendenhall", file_id: "2012_44")
Neighborhood.create(name: "N 8th - N 9th", file_id: "2012_45")
Neighborhood.create(name: "3rd - 4th - 5th - 6th between Peach and Villard", file_id: "2012_46")
Neighborhood.create(name: "Peach - Grand - Black - Villard", file_id: "2012_47")
Neighborhood.create(name: "Peach - 3rd - Tamarack - Tracy", file_id: "2012_48")
Neighborhood.create(name: "Main - 7th - Villard - Willson", file_id: "2012_49")
Neighborhood.create(name: "Peach - Black - Tamarack - Rouse", file_id: '2012_50')
Neighborhood.create(name: "Beall Park Area", file_id: "2012_51")
Neighborhood.create(name: "Peach - Rouse - Tamarack - Front", file_id: "2012_53")
Neighborhood.create(name: "Lamme - Rouse - Peach - Church", file_id: "2012_54")
Neighborhood.create(name: "Kock - 15th - Babcock - 11th", file_id: "2012_55")
Neighborhood.create(name: "College - Dickerson - 8th", file_id: "2012_56")
Neighborhood.create(name: "Story - 15th - Koch - 8th", file_id: "2012_57")
Neighborhood.create(name: "Olive - 11th - Main - 4th", file_id: "2012_58")
Neighborhood.create(name: "Koch - 11th - Curtiss", file_id: "2012_59")
Neighborhood.create(name: "Dickerson - 8th - Story - Willson", file_id: "2012_60")
Neighborhood.create(name: "College - 8th - Alderson - Willson", file_id: "2012_61")
Neighborhood.create(name: "Koch - 3rd - Olive - Lindley Pl", file_id: "2012_62")
Neighborhood.create(name: "Willson - Tracy - College - Koch", file_id: "2012_63")
Neighborhood.create(name: "Cleveland - 8th - Harrison - 3rd", file_id: "2012_64")
Neighborhood.create(name: "Garfield - 7th - Arthur - Willson", file_id: "2012_65")
Neighborhood.create(name: "Garfield - Willson - College - Black", file_id: "2012_66")
Neighborhood.create(name: "Mason - Black - Cleveland - Rouse", file_id: "2012_67")
Neighborhood.create(name: "Grant - 6th - Hayes - Willson", file_id: "2012_68")
Neighborhood.create(name: "Bonner - Rouse - Babcock - Wallace", file_id: "2012_69")
Neighborhood.create(name: "Meadow Creek", file_id: "2012_70")
Neighborhood.create(name: "Fieldview Circle", file_id: "2012_71")
Neighborhood.create(name: "Westgate South", file_id: "2012_72")
Neighborhood.create(name: "Harvest Creek SW", file_id: "2012_73")
Neighborhood.create(name: "Harvest Creek NE", file_id: "2012_74")
Neighborhood.create(name: "Harvest Creek - New Holland - Median - Durham", file_id: "2012_75")
Neighborhood.create(name: "Brentwood - Woodland - Maplewood - Mountain Ash", file_id: "2012_76")
Neighborhood.create(name: "Mineral - Sanders between Durston and Babcock", file_id: "2012_77")
Neighborhood.create(name: "Yellowstone - Durston - Babcock", file_id: "2012_78")
Neighborhood.create(name: "Babcock - Cameahwait - Droulliard", file_id: "2012_79")
Neighborhood.create(name: "Babcock - Michael Grove", file_id: "2012_80")
Neighborhood.create(name: "Villard - Michael Grove", file_id: "2012_81")
Neighborhood.create(name: "25th - Mendenhall - Durston", file_id: "2012_82")
Neighborhood.create(name: "Babcock - 24th - Beall", file_id: "2012_83")
Neighborhood.create(name: "19th - 20th - 21st between Durston and Beall", file_id: "2012_84")
Neighborhood.create(name: "Arnold - Circle", file_id: "2012_85")
Neighborhood.create(name: "Graf - 3rd - Henderson", file_id: "2012_86")
Neighborhood.create(name: "Wagonwheel East", file_id: "2012_88")
Neighborhood.create(name: "Sundance Springs", file_id: "2012_89")
Neighborhood.create(name: "Cedarview - Spruce", file_id: "2012_90")
Neighborhood.create(name: "OConnell - Kenyon", file_id: "2012_91")
Neighborhood.create(name: "Cherry - Firecrest - Ash - Maple - Holly", file_id: "2012_92")
Neighborhood.create(name: "Bozeman Trail", file_id: "2012_93")
Neighborhood.create(name: "Bogart Neighborhood", file_id: "2012_94")
Neighborhood.create(name: "N 10th - N 11th", file_id: "2012_95")
Neighborhood.create(name: "Village Downtown", file_id: "2012_97")
Neighborhood.create(name: "Koch - 15th - Babcock - 11th", file_id: "2012_98")
Neighborhood.create(name: "Alderson - Black - Story - Dell Pl", file_id: "2012_99")
Neighborhood.create(name: "Accola - Hoffman - Rouse", file_id: "2012_100")
Neighborhood.create(name: "Kagy - Greek Way - 3rd - Grand", file_id: "2012_101")
Neighborhood.create(name: "Elk Grove 3", file_id: "2012_102")
Neighborhood.create(name: "Elk Grove 2", file_id: "2012_103")
Neighborhood.create(name: "Elk Grove 1", file_id: "2012_104")
Neighborhood.create(name: "River Rock - Magnolia - Thorpe", file_id: "2012_105")
Neighborhood.create(name: "River Rock - West Shore - Shallow Brook - Green Tree", file_id: "2012_106")
Neighborhood.create(name: "River Rock - Royal - Engberg - Shallow Brook", file_id: "2012_107")
Neighborhood.create(name: "River Rock - Pebble Brook - West Shore", file_id: "2012_108")
Neighborhood.create(name: "River Rock - Amsterdam - Sibley - Thorpe", file_id: "2012_109")
Neighborhood.create(name: "River Rock - Woodsman - Thorpe" , file_id: "2012_110")
Neighborhood.create(name: "Happy - Golden West - Westwood - Cruiser", file_id: "2012_111")
Neighborhood.create(name: "Golden West - Jackrabbit - Cruiser - Spooner", file_id: "2012_112")
Neighborhood.create(name: "Westwood Circle - Oakwood - Jackrabbit", file_id: "2012_113")
Neighborhood.create(name: "Mayfair - Jackrabbit - Golden West", file_id: "2012_114")
Neighborhood.create(name: "Frontage - 13th - Park - 9th", file_id: "2012_115")
Neighborhood.create(name: "Frontage - 9th - Allison - 6th", file_id: "2012_116")
Neighborhood.create(name: "McEwen - Spooner - Al", file_id: "2012_117")
Neighborhood.create(name: "Central - Jackrabbit - Triple Crown - Spooner", file_id: "2012_118")
Neighborhood.create(name: "Central - Hoffman - Cameron - Weaver", file_id: "2012_119")
Neighborhood.create(name: "Central - Weaver - Cameron", file_id: "2012_120")
Neighborhood.create(name: "Rosebud - Oregon - Madison", file_id: "2012_121")
Neighborhood.create(name: "Silverbow - Oregon - Northern Pacific", file_id: "2012_122")
Neighborhood.create(name: "Yellowstone - Oregon - Silverbow", file_id: "2012_123")
Neighborhood.create(name: "Stiles - Rosebud - Jeanette Pl", file_id: "2012_124")
Neighborhood.create(name: "Idaho - Las Campanas - Wyoming", file_id: "2012_125")
Neighborhood.create(name: "Meadowbrook Estates South", file_id: "2012_127")
Neighborhood.create(name: "Meadowbrook Estates North", file_id: "2012_128")